### ISSUE TITLE
more explanation of Lemma1 and Lemma 2 

### ISSUE THREAD

**Issue by fikry102** [Haoqing-Wang/CDFSL-ATA#2]
Dear authors:
I find no supplementary material for the paper "Cross-Domain Few-Shot Classification via Adversarial Task Augmentation".
The conclusions in Lemma1 and Lemma 2 seem a little hard to deduce by myself. And the given references are full of too much distractors that I can't grasp the key content.
Could you please give me more explanation or some proof material about Lemma1 and Lemma 2?

**Comment by Haoqing-Wang** [comment]
The proof material has been added to our extension version for AIJ, and we will release it after the final decision.
