### ISSUE TITLE
About results in table1 

### ISSUE THREAD

**Issue by ideal-123** [Haoqing-Wang/CDFSL-ATA#4]
Hi, thanks for you sharing codes. Here I have a question about which model exactly you used when test in cross-domain few-shot dataset in table 1. For example, you use the one tested best in mini-test or you have another evaluation to choose the model which can generalize best in all this datasets? Looking forward to your response, thanks.

**Comment by Haoqing-Wang** [comment]
Thanks for you focus on our work. We use the validation split of source domain dataset (e.g., miniImageNet) to choose the best model and hyper-parameters.
